### ISSUE TITLE
Missing dependency: shelve

### ISSUE THREAD

**Issue by jeremydw** [google/budou#11]
Hi @tushuhei -- we're finally getting around to importing budou into https://github.com/grow/grow and noticed that the `shelve` dependency isn't enumerated in this project's `setup.py` and so we're getting "ImportError: No module named shelve". Is the correct fix to add it to `setup.py`?

**Comment by jeremydw** [comment]
Actually, this doesn't seem right -- `shelve` is part of the stdlib (https://docs.python.org/2/library/shelve.html). I'll have to do a little more investigation and will close this issue if it's a problem with our build environment instead.

**Comment by jeremydw** [comment]
Yep -- gonna close this one out. It was a weird issue with our build environment. We ended up fixing it by vendoring `shelve` into the project.

**Comment by tushuhei** [comment]
> we're finally getting around to importing budou into https://github.com/grow/grow
Woohoo! That's a great news! Please let me know if there's anything I can help.
